### ISSUE TITLE
Transformer部分一个链接失效

### ISSUE THREAD

**Issue by LiShaoyu5** [km1994/NLP-Interview-Notes#12]
[【关于 Transformer 问题及改进】那些你不知道的事](https://github.com/km1994/NLP-Interview-Notes/blob/main/DeepLearningAlgorithm/transformer/transformer_error.md)](https://github.com/km1994/NLP-Interview-Notes/blob/main/DeepLearningAlgorithm/transformer/transformer_error.md) 
现在是page not found状态，

**Comment by km1994** [comment]
你好，由于 目录结构 之前改动过，所以导致 主页 的 链接 生效，如果想看可以从 文件目录 点进去看哦。给你的学习造成不便，真的很抱歉。
