### ISSUE TITLE
很多latex符号无法加载

### ISSUE THREAD

**Issue by hackerchenzhuo** [km1994/NLP-Interview-Notes#2]
如题，lz是不是直接从latex文档复制过来的以至于github无法直接支撑

**Comment by km1994** [comment]
你浏览器装了插件了么？我这边是可以的，我用vs code

**Comment by hackerchenzhuo** [comment]
![image](https://user-images.githubusercontent.com/42081540/112254654-e97c7780-8c9b-11eb-883f-ebf69b933ca9.png)
如图...

**Comment by dh12306** [comment]
同问，怎么在网页上显示啊，需要装什么插件？ @km1994
