### ISSUE TITLE
NLP百面百搭 中 【关于 BatchNorm vs LayerNorm】部分的最后一个公式疑似错误

### ISSUE THREAD

**Issue by JuniorSummer** [km1994/NLP-Interview-Notes#9]
梯度计算应该是对变量求偏导，故应该将
![image](https://user-images.githubusercontent.com/53287966/146698743-c0e5cde1-e5c0-4f71-9623-58e2e93e005a.png)
替换为
![image](https://user-images.githubusercontent.com/53287966/146698756-108dfd7a-1e1e-402f-b1f0-ad3e2f1c3243.png)

**Comment by km1994** [comment]
嗯嗯，好的，已改
